### ISSUE TITLE
No named parameter with the name 'isMaterialAppTheme'.

### ISSUE THREAD

**Issue by paraggupta9065** [iampawan/VelocityX#57]
**Describe the bug**
this bug arises when I run my code

FAILURE: Build failed with an exception.

* Where:
Script '/home/parag/snap/flutter/common/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 997

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/parag/snap/flutter/common/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
        isMaterialAppTheme: isMaterialAppTheme,
        ^^^^^^^^^^^^^^^^^^
../../../../snap/flutter/common/flutter/packages/flutter/lib/src/material/theme.dart:40:9: Context: Found this candidate, but the arguments don't match.
  const Theme({
        ^^^^^
../../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/velocity_x-1.0.1/lib/src/flutter/theme.dart:47:9: Error: No named parameter with the name 'isMaterialAppTheme'.
        isMaterialAppTheme: isMaterialAppTheme,
        ^^^^^^^^^^^^^^^^^^
../../../../snap/flutter/common/flutter/packages/flutter/lib/src/material/theme.dart:40:9: Context: Found this candidate, but the arguments don't match.
  const Theme({
        ^^^^^
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by iampawan** [comment]
Update to v1.3.1 and it should be fixed

**Comment by paraggupta9065** [comment]
Ok will try it

**Comment by cyberianzed** [comment]
> **Describe the bug**
> this bug arises when I run my code
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
>   Script '/home/parag/snap/flutter/common/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 997
> * What went wrong:
>   Execution failed for task ':app:compileFlutterBuildDebug'.
> 
> > Process 'command '/home/parag/snap/flutter/common/flutter/bin/flutter'' finished with non-zero exit value 1
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 14s
> isMaterialAppTheme: isMaterialAppTheme,
> ^^^^^^^^^^^^^^^^^^
> ../../../../snap/flutter/common/flutter/packages/flutter/lib/src/material/theme.dart:40:9: Context: Found this candidate, but the arguments don't match.
> const Theme({
> ^^^^^
> ../../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/velocity_x-1.0.1/lib/src/flutter/theme.dart:47:9: Error: No named parameter with the name 'isMaterialAppTheme'.
> isMaterialAppTheme: isMaterialAppTheme,
> ^^^^^^^^^^^^^^^^^^
> ../../../../snap/flutter/common/flutter/packages/flutter/lib/src/material/theme.dart:40:9: Context: Found this candidate, but the arguments don't match.
> const Theme({
> ^^^^^
> Exception: Gradle task assembleDebug failed with exit code 1


I'm also having the same issue...
Any fixes...?

**Comment by iampawan** [comment]
Update your Velocityx version

**Comment by cyberianzed** [comment]
dependencies:
  flutter:
    sdk: flutter
    

  cupertino_icons: ^1.0.2
  backdrop: ^0.6.0
  font_awesome_flutter: ^9.0.0
  velocity_x: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
![image](https://user-images.githubusercontent.com/74711019/116004366-11a32180-a620-11eb-8c38-86056db74973.png)

Still..not fixed
